# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai_server.proto import dance_video_pb2 as ai__server_dot_proto_dot_dance__video__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_server/proto/dance_video_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DanceVideoStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamDanceVideo = channel.stream_stream(
                '/ai_server.proto.DanceVideoStreamService/StreamDanceVideo',
                request_serializer=ai__server_dot_proto_dot_dance__video__pb2.DanceVideoChunk.SerializeToString,
                response_deserializer=ai__server_dot_proto_dot_dance__video__pb2.DanceVideoProgress.FromString,
                _registered_method=True)


class DanceVideoStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamDanceVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DanceVideoStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamDanceVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDanceVideo,
                    request_deserializer=ai__server_dot_proto_dot_dance__video__pb2.DanceVideoChunk.FromString,
                    response_serializer=ai__server_dot_proto_dot_dance__video__pb2.DanceVideoProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_server.proto.DanceVideoStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_server.proto.DanceVideoStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DanceVideoStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamDanceVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai_server.proto.DanceVideoStreamService/StreamDanceVideo',
            ai__server_dot_proto_dot_dance__video__pb2.DanceVideoChunk.SerializeToString,
            ai__server_dot_proto_dot_dance__video__pb2.DanceVideoProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
