# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_server/proto/dance_video.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_server/proto/dance_video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ai_server/proto/dance_video.proto\x12\x0f\x61i_server.proto\"Q\n\x0f\x44\x61nceVideoChunk\x12\x13\n\x0bvideo_chunk\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\"\xbb\x01\n\x12\x44\x61nceVideoProgress\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\x05\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\x17\n\x0f\x63\x61lories_burned\x18\x05 \x01(\x01\x12\x16\n\x0etotal_calories\x18\x06 \x01(\x01\x12\x16\n\x0emovement_score\x18\x07 \x01(\x01\x12\x13\n\x0b\x63urrent_met\x18\x08 \x01(\x01\x32x\n\x17\x44\x61nceVideoStreamService\x12]\n\x10StreamDanceVideo\x12 .ai_server.proto.DanceVideoChunk\x1a#.ai_server.proto.DanceVideoProgress(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_server.proto.dance_video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DANCEVIDEOCHUNK']._serialized_start=54
  _globals['_DANCEVIDEOCHUNK']._serialized_end=135
  _globals['_DANCEVIDEOPROGRESS']._serialized_start=138
  _globals['_DANCEVIDEOPROGRESS']._serialized_end=325
  _globals['_DANCEVIDEOSTREAMSERVICE']._serialized_start=327
  _globals['_DANCEVIDEOSTREAMSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
